'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace WebApplication1.CustomControls


	Partial Public Class CustomAppointmentForm

		''' <summary>
		''' ASPxLabelSubject control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxLabelSubject As Global.DevExpress.Web.ASPxLabel

		''' <summary>
		''' ASPxTextBoxSubject control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxTextBoxSubject As Global.DevExpress.Web.ASPxTextBox

		''' <summary>
		''' ASPxLabelStart control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxLabelStart As Global.DevExpress.Web.ASPxLabel

		''' <summary>
		''' ASPxDateEditStart control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxDateEditStart As Global.DevExpress.Web.ASPxDateEdit

		''' <summary>
		''' ASPxLabelEnd control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxLabelEnd As Global.DevExpress.Web.ASPxLabel

		''' <summary>
		''' ASPxDateEditEnd control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxDateEditEnd As Global.DevExpress.Web.ASPxDateEdit

		''' <summary>
		''' ASPxLabelDescription control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxLabelDescription As Global.DevExpress.Web.ASPxLabel

		''' <summary>
		''' ASPxMemoDescription control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxMemoDescription As Global.DevExpress.Web.ASPxMemo

		''' <summary>
		''' ASPxLabelCustomInfo control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxLabelCustomInfo As Global.DevExpress.Web.ASPxLabel

		''' <summary>
		''' ASPxTextBoxCustomInfo control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxTextBoxCustomInfo As Global.DevExpress.Web.ASPxTextBox

		''' <summary>
		''' ASPxLabel1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxLabel1 As Global.DevExpress.Web.ASPxLabel

		''' <summary>
		''' ASPxUploadControl1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxUploadControl1 As Global.DevExpress.Web.ASPxUploadControl

		''' <summary>
		''' ASPxLabelFileName control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxLabelFileName As Global.DevExpress.Web.ASPxLabel

		''' <summary>
		''' ASPxButtonOk control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxButtonOk As Global.DevExpress.Web.ASPxButton

		''' <summary>
		''' ASPxButtonCancel control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxButtonCancel As Global.DevExpress.Web.ASPxButton

		''' <summary>
		''' ASPxButtonDelete control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxButtonDelete As Global.DevExpress.Web.ASPxButton
	End Class
End Namespace
